// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnebhesaxxlglaaxtcve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZWJoZXNheHhsZ2xhYXh0Y3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODk5MTcsImV4cCI6MjA1NjQ2NTkxN30.vw6EDy_i4NTy5hbnNIqx2jGJGjvNu8imbW27zsPk4Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);